[package]
name = "while-lang"
version = "0.1.0"
description = "An interpreter for the WHILE programming language"
edition = "2018"

[dependencies]
num-traits = "0.2"
num-integer = "0.1"
num-bigint = "0.4"

clap = "3.0.0-beta.4"
codespan-reporting = "0.11"
